### ISSUE TITLE
Question: What is the intented behavior when using the appcache package?

### ISSUE THREAD

**Issue by miri-am** [255kb/meteor-status#10]
Was just wondering, because it does not seem to show when appcache is used and server is disconnected?

**Comment by 255kb** [comment]
Hi, 
The package is using `Meteor.status()` to check whether the app is connected or not but I don't see how the appcache package could change the connection status. 
I will have a look at this.

**Comment by miri-am** [comment]
sorry, I dont remember how I concluded that the appcache package could be the reason. Was a mistake in my configuration - working as expected: thanks!

**Comment by 255kb** [comment]
no problem, glad it is working now :smile:
