### ISSUE TITLE
Any plans for a React version?

### ISSUE THREAD

**Issue by marbemac** [255kb/meteor-status#13]

**Comment by 255kb** [comment]
I did not try React yet, and have little to no time at the moment.
I will surely do something once I learn React but in the meantime if you want to submit a PR you are more than welcome :)

**Comment by marbemac** [comment]
Sure thing, in that case we'll probably take it on. We could do a pr, if you're willing to switch the entire package over to react, and drop blaze? Otherwise we can fork and maintain the react version there. Let me know!

We'll likely also do it with Meteor 1.3 in mind (ie pulling React in from npm, not atmosphere).

**Comment by 255kb** [comment]
I really would like to keep the Blaze version up and running for a while.
Isn't there a way to have different versions (Blaze/React) in the same package?
If not feel free to fork :)

**Comment by arthurkirsz** [comment]
Why don't you just create a specific branch for the react version (easy for us to download and make the difference :D)

**Comment by marbemac** [comment]
Yeah that would work, but the convention in the community seems to be creating a separate repo (meteor-status-react, meteor-react-status, etc). For example, what sAlert and react-layout did.

We're most likely going to get to this when 1.3 RC comes out, unless somebody gets to it first :). For now, we're loading blaze and react - just increases the filesize a bit.

**Comment by Siyfion** [comment]
@marbemac Any progress on this? I'd love to use a React version of this!

**Comment by marbemac** [comment]
@Siyfion nope not yet, haven't had time to get to it.
