### ISSUE TITLE
Timeout to check for status

### ISSUE THREAD

**Issue by bluefangs** [255kb/meteor-status#18]
Hello - 
I have a method call that is rather heavy on the server side. During which time, I end up with an "unable to reach server" error, even though the server is very much up and running (Just that it's too busy at the moment to respond). Is there a way to have a custom timeout option to begin checking for server connection status? 

Thanks.

**Comment by 255kb** [comment]
Hello, 

I am not maintaining this package anymore, but feel free to submit a merge request with a custom timeout system.
