### ISSUE TITLE
Add "Smart Disconnect" features?

### ISSUE THREAD

**Issue by steph643** [255kb/meteor-status#2]
Got the feeling the ideal package would have the combined features of this package and of [smart disconnect](https://github.com/mixmaxhq/meteor-smart-disconnect)...

**Comment by taromero** [comment]
@steph643 I don't see why adding this 2 packages separately wouldn't work. Thanks for pointing out smart-disconnect, it seems interesting.

**Comment by 255kb** [comment]
I plan to make this compatible with Smart Disconnect (rather to redevelop this feature) which is not the case at the moment (the alert shows up event if the app is voluntarily disconnected).

**Comment by steph643** [comment]
Advantage of a unique package:
- from a user perspective: one single entry point and documentation for closely related features.
- from a programmer perspective: better integration, no need to maintain compatibility with a third party package that might evolve in unpredictable ways.

But I confess this was a bit provocative. This package is very young and it might not be the time to plan for more features or for joining with another team.

**Comment by 255kb** [comment]
I understand the advantages, maybe in a next release :) 
For now, I've added support for "voluntarily" disconnect (with `Meteor.disconnect()`) and thus Smart Disconnect package. 
Now the alert won't show up when the disconnect is voluntary.
